services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8001:8000" # Puerto personalizado para evitar conflictos
    volumes:
      - .:/var/www
    depends_on:
      - db
    dns:
      - 8.8.8.8

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306" # Puerto cambiado para evitar conflicto con MySQL local
    volumes:
      - db_data:/var/lib/mysql
    dns:
      - 8.8.8.8

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"  # Puedes cambiar el puerto si lo necesitas
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    depends_on:
      - db

volumes:
  db_data: